[package]
name = "zerus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.2"
clap = { version = "3.2.14", features = ["derive"] }
toml = "0.5.9"
reqwest = { version = "0.11.11", default-features = false, features = ["blocking", "rustls-tls"] }
anyhow = "1.0.58"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
thiserror = "1.0.31"
warp = "0.3.2"
bytes = "1.2.0"
futures-util = "0.3.21"
tokio-util = "0.7.3"
tokio-stream = "0.1.9"
pretty_env_logger = "0.4.0"

[profile.release]
lto = true
strip = true

[[bin]]
path = "src/serve.rs"
name = "zerus-serve"
