[package]
name = "zerus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.2"
clap = { version = "3.2.14", features = ["derive"] }
toml = "0.5.9"
reqwest = { version = "0.11.11", features = ["blocking"] }
anyhow = "1.0.58"
