[package]
name = "zerus"
version = "0.2.0"
edition = "2021"
authors = ["wcampbell"]
description = "Lightweight binary to download only project required crates for offline crates.io mirror"
license = "MIT/Apache-2.0"
readme = "README.md"
homepage = "https://github.com/wcampbell0x2a/zerus"
repository = "https://github.com/wcampbell0x2a/zerus"

[dependencies]
walkdir = "2.3.2"
clap = { version = "3.2.14", features = ["derive"] }
toml = "0.5.9"
reqwest = { version = "0.11.11", default-features = false, features = ["blocking", "rustls-tls"] }
anyhow = "1.0.58"

[profile.release]
lto = true
strip = true
